uk.org.primrose.pool.CannotConnectException: Cannot connect to db using driver (com.mysql.jdbc.Driver), url(jdbc:mysql://10.199.38.102:3306/smsgw), username(root)
	at uk.org.primrose.Util.getConnection(Util.java:123)
	at uk.org.primrose.pool.core.Pool.loadConnection(Pool.java:457)
	at uk.org.primrose.pool.core.Pool.start(Pool.java:570)
	at uk.org.primrose.pool.core.PoolLoader.loadPool(PoolLoader.java:302)
	at uk.org.primrose.pool.core.PoolLoader.loadPool(PoolLoader.java:125)
	at uk.org.primrose.vendor.standalone.PrimroseLoader.load(PrimroseLoader.java:70)
	at com.vasc.smpp.gateway.DBPool.ConfigDB(DBPool.java:208)
	at com.vasc.smpp.cdr.CDRServer.<init>(CDRServer.java:30)
	at com.vasc.smpp.cdr.CDRServer.main(CDRServer.java:39)
Caused by: java.sql.SQLException: Access denied for user 'root'@'10.199.38.101' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3938)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:298)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at uk.org.primrose.Util.getConnection(Util.java:116)
	... 8 more
uk.org.primrose.pool.CannotConnectException: Cannot connect to db using driver (com.mysql.jdbc.Driver), url(jdbc:mysql://10.199.38.102:3306/reportsms), username(root)
	at uk.org.primrose.Util.getConnection(Util.java:123)
	at uk.org.primrose.pool.core.Pool.loadConnection(Pool.java:457)
	at uk.org.primrose.pool.core.Pool.start(Pool.java:570)
	at uk.org.primrose.pool.core.PoolLoader.loadPool(PoolLoader.java:302)
	at uk.org.primrose.pool.core.PoolLoader.loadPool(PoolLoader.java:149)
	at uk.org.primrose.vendor.standalone.PrimroseLoader.load(PrimroseLoader.java:70)
	at com.vasc.smpp.gateway.DBPool.ConfigDB(DBPool.java:208)
	at com.vasc.smpp.cdr.CDRServer.<init>(CDRServer.java:30)
	at com.vasc.smpp.cdr.CDRServer.main(CDRServer.java:39)
Caused by: java.sql.SQLException: Access denied for user 'root'@'10.199.38.101' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3938)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:298)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at uk.org.primrose.Util.getConnection(Util.java:116)
	... 8 more
